### ISSUE TITLE
Error when opening core on Ubuntu

### ISSUE THREAD

**Issue by Satellaa** [DyXel/Multirole#18]
I got the following error while running `terminate called after throwing an instance of 'std::runtime_error'
  what():  tmp/1697703643932353506-0-libocgcore.so: cannot open shared object file: No such file or directory`

I am sure that the original core file `libocgcore.so` is in the `sync/bin` folder and has been successfully copied to the `tmp` folder.

Here are the commands I used:
```
meson setup build && meson compile -C build
cd build
./multirole
```

**Comment by DyXel** [comment]
I cannot reproduce locally. Would you mind sharing which architecture you are on and the config.json you used?

**Comment by Satellaa** [comment]
> I cannot reproduce locally. Would you mind sharing which architecture you are on and the config.json you used?

I'm on `aarch64` and the config file is Multirole's default file, no modifications

**Comment by DyXel** [comment]
the .so file in our ProjectIgnis/bin repo is `x86_64`, so it wouldn't run on `aarch64` by default. I would have expected the diagnostic from `dlerror` to be more specific... In any case, what you'd need to do is compile the core manually for your platform and configure it like you would any other repo.

**Comment by Satellaa** [comment]
> the .so file in our ProjectIgnis/bin repo is `x86_64`, so it wouldn't run on `aarch64` by default. I would have expected the diagnostic from `dlerror` to be more specific... In any case, what you'd need to do is compile the core manually for your platform and configure it like you would any other repo.

You are right, I have successfully run the server after complieing the core for my platform
```[2023-10-19 19:02:14.563] [Service:Multirole] [Level:Info] Initialization finished successfully!```

So, for those who have the same problem as me, you just need to clone ygopro-core of `edo9300` and compile it with meson like you did with Multirole.
