### ISSUE TITLE
concurrencyHint negative value uses twice the number of threads instead of cores

### ISSUE THREAD

**Issue by CDGCodes** [DyXel/Multirole#21]
The documentation lists that having a negative value in the "concurrencyHint" field will make the server use all the threads of a CPU, or twice the number of cores
On my Ryzen 9 3900x with 12 cores and 24 threads, a negative value tries to run the server with 48 threads. Doing this also prevented me from connecting on the client (switching this to a value of 16 solved that issue)
I'm running this on Ubuntu 22.04 LTS

**Comment by DyXel** [comment]
Documentation seems correct, recall:

> putting a negative value lets Multirole decide the amount, which is **usually** the machine's CPU cores times 2.

(emphasis on the bold part). It's not really a guarantee, which is also why its called concurrency**Hint**. So if you ever need a different value, set it manually.

> Doing this also prevented me from connecting on the client (switching this to a value of 16 solved that issue)

This seems like a separate problem. When we talk about threads in the context of the server, its threads of execution, unrelated to the CPU cores. The operating system is free to schedule those threads of execution however it sees fit, and unless you have hundreds of rooms running simultaneously, most of those threads will be sleeping (waiting for work to do).

**Comment by DyXel** [comment]
Tested with 128 threads on my machine and couldn't reproduce the second part of your issue.
